import { Hashtag } from '../exploreSlice';

export const mockHashtags: Hashtag[] = [
  {
    id: 'hashtag-1',
    name: 'travel',
    postsCount: 1250000,
    isFollowing: false,
    category: 'trending',
  },
  {
    id: 'hashtag-2',
    name: 'food',
    postsCount: 890000,
    isFollowing: true,
    category: 'trending',
  },
  {
    id: 'hashtag-3',
    name: 'fashion',
    postsCount: 750000,
    isFollowing: false,
    category: 'fashion',
  },
  {
    id: 'hashtag-4',
    name: 'fitness',
    postsCount: 650000,
    isFollowing: true,
    category: 'sports',
  },
  {
    id: 'hashtag-5',
    name: 'photography',
    postsCount: 980000,
    isFollowing: false,
    category: 'trending',
  },
  {
    id: 'hashtag-6',
    name: 'art',
    postsCount: 420000,
    isFollowing: false,
    category: 'entertainment',
  },
  {
    id: 'hashtag-7',
    name: 'nature',
    postsCount: 1100000,
    isFollowing: true,
    category: 'trending',
  },
  {
    id: 'hashtag-8',
    name: 'music',
    postsCount: 780000,
    isFollowing: false,
    category: 'entertainment',
  },
  {
    id: 'hashtag-9',
    name: 'tech',
    postsCount: 560000,
    isFollowing: false,
    category: 'news',
  },
  {
    id: 'hashtag-10',
    name: 'sports',
    postsCount: 690000,
    isFollowing: true,
    category: 'sports',
  },
  {
    id: 'hashtag-11',
    name: 'style',
    postsCount: 450000,
    isFollowing: false,
    category: 'fashion',
  },
  {
    id: 'hashtag-12',
    name: 'cooking',
    postsCount: 380000,
    isFollowing: false,
    category: 'food',
  },
  {
    id: 'hashtag-13',
    name: 'workout',
    postsCount: 320000,
    isFollowing: true,
    category: 'sports',
  },
  {
    id: 'hashtag-14',
    name: 'beach',
    postsCount: 290000,
    isFollowing: false,
    category: 'trending',
  },
  {
    id: 'hashtag-15',
    name: 'adventure',
    postsCount: 410000,
    isFollowing: false,
    category: 'trending',
  },
];