import { User, FriendRequest } from '../friendSlice';

export const mockFriends: User[] = [
  {
    id: 'friend1',
    name: 'Nguyễn Minh A',
    username: 'minha_99',
    avatar: 'https://picsum.photos/60/60?random=201',
    isFollowing: true,
    isFollowingYou: true,
    mutualFriends: 12,
    isCloseFriend: true,
    isBlocked: false,
    isVerified: true,
    bio: 'Photographer & Travel lover 📸',
  },
  {
    id: 'friend2',
    name: 'Trần Thu B',
    username: 'thub_travel',
    avatar: 'https://picsum.photos/60/60?random=202',
    isFollowing: true,
    isFollowingYou: true,
    mutualFriends: 8,
    isCloseFriend: false,
    isBlocked: false,
    isVerified: false,
    bio: 'Food blogger 🍜',
  },
  {
    id: 'friend3',
    name: 'Lê Văn C',
    username: 'vanc_music',
    avatar: 'https://picsum.photos/60/60?random=203',
    isFollowing: true,
    isFollowingYou: true,
    mutualFriends: 15,
    isCloseFriend: true,
    isBlocked: false,
    isVerified: true,
    bio: 'Musician & Producer 🎵',
  },
  {
    id: 'friend4',
    name: 'Phạm Thu D',
    username: 'thud_art',
    avatar: 'https://picsum.photos/60/60?random=204',
    isFollowing: true,
    isFollowingYou: false,
    mutualFriends: 3,
    isCloseFriend: false,
    isBlocked: false,
    isVerified: false,
    bio: 'Digital artist 🎨',
  },
];

export const mockSuggestedUsers: User[] = [
  {
    id: 'suggest1',
    name: 'Hoàng Minh E',
    username: 'minhe_photo',
    avatar: 'https://picsum.photos/60/60?random=301',
    isFollowing: false,
    isFollowingYou: false,
    mutualFriends: 5,
    isCloseFriend: false,
    isBlocked: false,
    isVerified: true,
    bio: 'Portrait photographer 📷',
  },
  {
    id: 'suggest2',
    name: 'Vũ Đức F',
    username: 'ducf_fitness',
    avatar: 'https://picsum.photos/60/60?random=302',
    isFollowing: false,
    isFollowingYou: false,
    mutualFriends: 3,
    isCloseFriend: false,
    isBlocked: false,
    isVerified: false,
    bio: 'Fitness trainer 💪',
  },
  {
    id: 'suggest3',
    name: 'Đỗ Lan G',
    username: 'lang_fashion',
    avatar: 'https://picsum.photos/60/60?random=303',
    isFollowing: false,
    isFollowingYou: false,
    mutualFriends: 7,
    isCloseFriend: false,
    isBlocked: false,
    isVerified: true,
    bio: 'Fashion designer ✨',
  },
  {
    id: 'suggest4',
    name: 'Bùi Quốc H',
    username: 'quoch_tech',
    avatar: 'https://picsum.photos/60/60?random=304',
    isFollowing: false,
    isFollowingYou: false,
    mutualFriends: 2,
    isCloseFriend: false,
    isBlocked: false,
    isVerified: false,
    bio: 'Software developer 💻',
  },
  {
    id: 'suggest5',
    name: 'Cao Thu I',
    username: 'thui_cooking',
    avatar: 'https://picsum.photos/60/60?random=305',
    isFollowing: false,
    isFollowingYou: false,
    mutualFriends: 1,
    isCloseFriend: false,
    isBlocked: false,
    isVerified: false,
    bio: 'Home chef 👩‍🍳',
  },
];

export const mockFriendRequests: FriendRequest[] = [
  {
    id: 'req1',
    user: {
      id: 'req_user1',
      name: 'Ngô Thanh J',
      username: 'thanhj_yoga',
      avatar: 'https://picsum.photos/60/60?random=401',
      isFollowing: false,
      isFollowingYou: true,
      mutualFriends: 4,
      isCloseFriend: false,
      isBlocked: false,
      isVerified: false,
      bio: 'Yoga instructor 🧘‍♀️',
    },
    timestamp: '2024-01-20T10:30:00Z',
    message: 'Xin chào! Tôi thấy chúng ta có nhiều bạn chung.',
  },
  {
    id: 'req2',
    user: {
      id: 'req_user2',
      name: 'Đinh Văn K',
      username: 'vank_travel',
      avatar: 'https://picsum.photos/60/60?random=402',
      isFollowing: false,
      isFollowingYou: true,
      mutualFriends: 2,
      isCloseFriend: false,
      isBlocked: false,
      isVerified: true,
      bio: 'Travel blogger ✈️',
    },
    timestamp: '2024-01-19T15:45:00Z',
  },
  {
    id: 'req3',
    user: {
      id: 'req_user3',
      name: 'Tô Minh L',
      username: 'minhl_design',
      avatar: 'https://picsum.photos/60/60?random=403',
      isFollowing: false,
      isFollowingYou: true,
      mutualFriends: 6,
      isCloseFriend: false,
      isBlocked: false,
      isVerified: false,
      bio: 'UI/UX Designer 🎨',
    },
    timestamp: '2024-01-18T09:20:00Z',
  },
];

export const mockBlockedUsers: User[] = [
  {
    id: 'blocked1',
    name: 'Spam User',
    username: 'spam_account',
    avatar: null,
    isFollowing: false,
    isFollowingYou: false,
    mutualFriends: 0,
    isCloseFriend: false,
    isBlocked: true,
    isVerified: false,
  },
];