import { Reel } from '../types';

export const mockReels: Reel[] = [
  {
    id: '1',
    userId: '2',
    userName: 'nghia404',
    avatarUrl: 'https://firebasestorage.googleapis.com/v0/b/savefileimage.appspot.com/o/avatars%2Fa4ec4232-a42c-4344-8c85-cbf2725fe599_480740910_1692283898302684_9055846236917448018_n+%281%29.jpg?alt=media',
    caption: 'My first reel! 🔥 Amazing dance moves',
    visibility: 'PUBLIC',
    tags: ['dance', 'reel', 'viral'],
    mediaUrl: 'https://firebasestorage.googleapis.com/v0/b/savefileimage.appspot.com/o/videos%2F5ee76c87-6464-485b-9e4e-5e192d8d81bf%2Findex.m3u8?alt=media',
    likesCount: 0,
    commentsCount: 0,
    isLiked: true,
    taggedUsers: [],
    isActive: true,
    createdAt: '2025-10-19T16:12:10.529',
    updatedAt: '2025-10-19T16:12:44.405',
  },
  {
    id: '2',
    userId: '3',
    userName: 'sports_fan',
    avatarUrl: 'https://via.placeholder.com/150',
    caption: 'Best sports moments of the week! 🏆 Don\'t miss these incredible plays!',
    visibility: 'PUBLIC',
    tags: ['sports', 'highlights', 'viral'],
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    likesCount: 125000,
    commentsCount: 2341,
    isLiked: false,
    taggedUsers: [
      { userId: 5, userName: 'friend1' },
      { userId: 6, userName: 'friend2' },
    ],
    isActive: true,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: '3',
    userId: '4',
    userName: 'fitnessguru',
    avatarUrl: 'https://via.placeholder.com/150',
    caption: '30-day challenge results! 💪 Keep pushing yourself! Consistency is key to success.',
    visibility: 'PUBLIC',
    tags: ['fitness', 'workout', 'motivation'],
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    likesCount: 89000,
    commentsCount: 1532,
    isLiked: true,
    taggedUsers: [],
    isActive: true,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: '4',
    userId: '5',
    userName: 'travelblogger',
    avatarUrl: 'https://via.placeholder.com/150',
    caption: 'Hidden gems in Japan 🗾✨ You need to add these to your bucket list!',
    visibility: 'PUBLIC',
    tags: ['travel', 'japan', 'adventure'],
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    likesCount: 203000,
    commentsCount: 4521,
    isLiked: false,
    taggedUsers: [],
    isActive: true,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    updatedAt: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: '5',
    userId: '6',
    userName: 'foodie_adventures',
    avatarUrl: 'https://via.placeholder.com/150',
    caption: 'The ultimate street food guide! 🍜🥟 Which one would you try first?',
    visibility: 'PUBLIC',
    tags: ['streetfood', 'foodie', 'yummy'],
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    likesCount: 156000,
    commentsCount: 3287,
    isLiked: false,
    taggedUsers: [
      { userId: 7, userName: 'chef123' },
    ],
    isActive: true,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    updatedAt: new Date(Date.now() - 432000000).toISOString(),
  },
];

