export const mockFriends = [
  {
    id: 'user1',
    name: 'Nguyễn Văn A',
    username: 'nguyenvana',
    avatar: 'https://picsum.photos/50/50?random=101',
    isOnline: true,
  },
  {
    id: 'user2',
    name: 'Trần Thị B',
    username: 'tranthib',
    avatar: 'https://picsum.photos/50/50?random=102',
    isOnline: false,
  },
  {
    id: 'user3',
    name: 'Lê Văn C',
    username: 'levanc',
    avatar: 'https://picsum.photos/50/50?random=103',
    isOnline: true,
  },
  {
    id: 'user4',
    name: 'Phạm Thu D',
    username: 'phamthud',
    avatar: 'https://picsum.photos/50/50?random=104',
    isOnline: false,
  },
  {
    id: 'user5',
    name: 'Hoàng Minh E',
    username: 'hoangminhe',
    avatar: 'https://picsum.photos/50/50?random=105',
    isOnline: true,
  },
  {
    id: 'user6',
    name: 'Vũ Đức F',
    username: 'vuducf',
    avatar: 'https://picsum.photos/50/50?random=106',
    isOnline: false,
  },
];

export const mockHashtags = [
  '#photography',
  '#travel',
  '#food',
  '#sunset',
  '#coffee',
  '#weekend',
  '#beautiful',
  '#nature',
  '#friends',
  '#family',
  '#work',
  '#fitness',
  '#health',
  '#music',
  '#art',
  '#love',
  '#happy',
  '#fun',
  '#adventure',
  '#relax',
];