export const mockPosts = [
  {
    id: '1',
    userId: '1',
    userName: 'Nguyễn Văn A',
    userAvatar: 'https://picsum.photos/40/40?random=101',
    content: 'Beautiful sunset from my balcony! 🌅 #sunset #photography #evening',
    media: [
      {
        id: 'm1',
      type: 'image' as const,
        url: 'https://picsum.photos/600/600?random=1',
        alt: 'Sunset view',
      },
    ],
    privacy: 'public' as const,
    taggedUsers: ['user2', 'user3'],
    hashtags: ['sunset', 'photography', 'evening'],
    location: 'Ho Chi Minh City, Vietnam',
    createdAt: '2024-01-15T18:30:00Z',
    updatedAt: '2024-01-15T18:30:00Z',
    likesCount: 124,
    commentsCount: 18,
    sharesCount: 5,
    isLiked: false,
    isBookmarked: true,
    isPinned: false,
    violationScore: 0.1,
  },
  {
    id: '6',
    userId: '6',
    userName: 'Demo Violation',
    userAvatar: 'https://picsum.photos/40/40?random=106',
    content: 'This is spam content with EXCESSIVE CAPS!!! Click here for fake news and scam offers!!!!!',
    media: [
      {
        id: 'm6',
        type: 'image' as const,
        url: 'https://picsum.photos/600/600?random=106',
        alt: 'Suspicious content',
      },
    ],
    privacy: 'public' as const,
    taggedUsers: [],
    hashtags: ['fake', 'spam'],
    location: 'Unknown Location',
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
    likesCount: 2,
    commentsCount: 0,
    sharesCount: 0,
    isLiked: false,
    isBookmarked: false,
    isPinned: false,
    violationScore: 0.85,
    violationType: 'spam',
  },
  {
    id: '2',
    userId: '2',
    userName: 'Trần Thị B',
    userAvatar: 'https://picsum.photos/40/40?random=102',
    content: 'Coffee time ☕ Perfect start to the weekend!',
    media: [
      {
        id: 'm2',
        type: 'image' as const,
        url: 'https://picsum.photos/600/400?random=2',
        alt: 'Coffee cup',
      },
      {
        id: 'm3',
        type: 'image' as const,
        url: 'https://picsum.photos/600/400?random=3',
        alt: 'Cafe interior',
      },
    ],
    privacy: 'friends' as const,
    taggedUsers: [],
    hashtags: ['coffee', 'weekend', 'relax'],
    createdAt: '2024-01-15T09:15:00Z',
    updatedAt: '2024-01-15T09:15:00Z',
    likesCount: 67,
    commentsCount: 12,
    sharesCount: 2,
    isLiked: true,
    isBookmarked: false,
    isPinned: false,
    violationScore: 0.05,
  },
  {
    id: '3',
    userId: '3',
    userName: 'Lê Văn C',
    userAvatar: 'https://picsum.photos/40/40?random=103',
    content: 'This content might violate community guidelines...',
    media: [
      {
        id: 'm4',
        type: 'image' as const,
        url: 'https://picsum.photos/600/600?random=4',
        alt: 'Flagged content',
      },
    ],
    privacy: 'public' as const,
    taggedUsers: [],
    hashtags: [],
    createdAt: '2024-01-15T14:20:00Z',
    updatedAt: '2024-01-15T14:20:00Z',
    likesCount: 23,
    commentsCount: 8,
    sharesCount: 0,
    isLiked: false,
    isBookmarked: false,
    isPinned: false,
    violationScore: 0.85,
    violationType: 'Nội dung không phù hợp',
  },
];

export const mockStories = [
  {
    id: 's1',
    userId: '1',
    media: {
      id: 'sm1',
      type: 'image' as const,
      url: 'https://picsum.photos/400/700?random=10',
      alt: 'Story 1',
    },
    text: 'Good morning! ☀️',
    backgroundColor: '#FF6B6B',
    duration: 5000,
    createdAt: '2024-01-15T08:00:00Z',
    expiresAt: '2024-01-16T08:00:00Z',
    viewsCount: 45,
    isViewed: false,
  },
  {
    id: 's2',
    userId: '2',
    media: {
      id: 'sm2',
      type: 'video' as const,
      url: 'https://sample-videos.com/zip/10/mp4/SampleVideo_360x240_1mb.mp4',
      thumbnail: 'https://picsum.photos/400/700?random=11',
      alt: 'Story video',
    },
    duration: 8000,
    createdAt: '2024-01-15T10:30:00Z',
    expiresAt: '2024-01-16T10:30:00Z',
    viewsCount: 78,
    isViewed: true,
  },
];

export const mockReels = [
  {
    id: 'r1',
    userId: '1',
    video: {
      id: 'rv1',
      type: 'video' as const,
      url: 'https://sample-videos.com/zip/10/mp4/SampleVideo_360x240_1mb.mp4',
      thumbnail: 'https://picsum.photos/400/700?random=20',
      alt: 'Reel video',
    },
    description: 'Amazing dance moves! 💃 #dance #trending #viral',
    music: {
      id: 'music1',
      name: 'Popular Song',
      artist: 'Artist Name',
    },
    hashtags: ['dance', 'trending', 'viral'],
    createdAt: '2024-01-15T16:45:00Z',
    likesCount: 892,
    commentsCount: 156,
    sharesCount: 43,
    isLiked: true,
  },
  {
    id: 'r2',
    userId: '3',
    video: {
      id: 'rv2',
      type: 'video' as const,
      url: 'https://sample-videos.com/zip/10/mp4/SampleVideo_360x240_1mb.mp4',
      thumbnail: 'https://picsum.photos/400/700?random=21',
      alt: 'Cooking reel',
    },
    description: 'Quick recipe for delicious pasta! 🍝',
    hashtags: ['cooking', 'recipe', 'food'],
    createdAt: '2024-01-15T12:20:00Z',
    likesCount: 456,
    commentsCount: 89,
    sharesCount: 27,
    isLiked: false,
  },
];