export const MockComments = [
  {
    id: "1",
    author: "Nguyễn Văn A",
    content: "Bài viết rất hay và bổ ích!",
    post: "Chia sẻ về chuyến du lịch...",
    likes: 12,
    reports: 0,
    date: "2024-11-10",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=1",
  },
  {
    id: "2",
    author: "Trần Thị B",
    content: "Không đồng ý với quan điểm này",
    post: "Thảo luận về công nghệ...",
    likes: 3,
    reports: 2,
    date: "2024-11-09",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=2",
  },
  {
    id: "3",
    author: "Lê Văn C",
    content: "Spam content here...",
    post: "Video hướng dẫn...",
    likes: 0,
    reports: 5,
    date: "2024-11-08",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=3",
  },
];

export const MockChartData = [
  { date: "01/11", users: 400, posts: 240, interactions: 1200, reports: 12 },
  { date: "05/11", users: 450, posts: 280, interactions: 1400, reports: 10 },
  { date: "10/11", users: 520, posts: 320, interactions: 1600, reports: 8 },
  { date: "15/11", users: 580, posts: 380, interactions: 1800, reports: 15 },
  { date: "20/11", users: 640, posts: 420, interactions: 2100, reports: 11 },
  { date: "25/11", users: 720, posts: 480, interactions: 2400, reports: 9 },
  { date: "30/11", users: 800, posts: 520, interactions: 2800, reports: 7 },
];

export const MockTopHashtags = [
  { tag: "#travel", count: 1250, trend: "+12%" },
  { tag: "#food", count: 980, trend: "+8%" },
  { tag: "#fashion", count: 875, trend: "+15%" },
  { tag: "#fitness", count: 720, trend: "+5%" },
  { tag: "#photography", count: 650, trend: "+10%" },
];

export const MockUsersFull = [
  {
    id: "1",
    name: "Nguyễn Văn A",
    email: "nguyenvana@email.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=1",
    role: "user",
    status: "active",
    joinDate: "2024-01-01",
    bio: "Yêu thích du lịch và nhiếp ảnh.",
    location: "Hà Nội",
    posts: 45,
    comments: 120,
    likes: 340,
    violations: 0,
    followers: 1200,
    following: 300,
    lastActive: "2025-11-13",
    interactions: 1200,
  },
  {
    id: "2",
    name: "Trần Thị B",
    email: "tranthib@email.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=2",
    role: "moderator",
    status: "active",
    joinDate: "2023-06-15",
    bio: "Moderator của cộng đồng.",
    location: "TP.HCM",
    posts: 120,
    comments: 340,
    likes: 980,
    violations: 1,
    followers: 5000,
    following: 450,
    lastActive: "2025-11-14",
    interactions: 1300,
  },
  {
    id: "3",
    name: "Lê Văn C",
    email: "levanc@email.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=3",
    role: "user",
    status: "locked",
    joinDate: "2024-02-20",
    bio: "Đam mê lập trình.",
    location: "Đà Nẵng",
    posts: 25,
    comments: 50,
    likes: 120,
    violations: 5,
    followers: 300,
    following: 150,
    lastActive: "2025-11-10",
    interactions: 40,
  },
  {
    id: "4",
    name: "Phạm Thị D",
    email: "phamthid@email.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=4",
    role: "user",
    status: "pending",
    joinDate: "2025-01-10",
    bio: "",
    location: "",
    posts: 0,
    comments: 0,
    likes: 0,
    violations: 0,
    followers: 0,
    following: 0,
    lastActive: "",
    interactions: 0,
  },
];
