import { UserProfile } from '../profileSlice';

export const mockUsers: UserProfile[] = [
  {
    id: 'user1',
    username: 'nghialc81',
    name: 'Lê Chí Nghĩa',
    avatar: 'https://picsum.photos/150/150?random=1',
    bio: 'Bình yên 🌸\nlocket.cam/nghialc',
    website: 'https://locket.cam/nghialc',
    isVerified: false,
    isPrivate: false,
    postsCount: 1,
    followersCount: 40,
    followingCount: 36,
    isFollowing: false,
    isFollowedBy: false,
    isBlocked: false,
    isMuted: false,
  },
  {
    id: 'user2',
    username: 'motchutnhi',
    name: 'motchutnhi',
    avatar: 'https://picsum.photos/150/150?random=2',
    bio: 'Creative soul ✨\nPhotographer & Designer',
    website: '',
    isVerified: true,
    isPrivate: false,
    postsCount: 127,
    followersCount: 1200,
    followingCount: 456,
    isFollowing: true,
    isFollowedBy: true,
    isBlocked: false,
    isMuted: false,
  },
  {
    id: 'user3',
    username: 'nguyentroang_',
    name: 'Nguyễn Trọng Hoàng',
    avatar: 'https://picsum.photos/150/150?random=3',
    bio: 'Travel enthusiast 🌍\nLife is an adventure',
    website: 'https://travelblog.com',
    isVerified: false,
    isPrivate: true,
    postsCount: 89,
    followersCount: 567,
    followingCount: 234,
    isFollowing: false,
    isFollowedBy: false,
    isBlocked: false,
    isMuted: false,
  },
  {
    id: 'user4',
    username: '_ahn.dzy_',
    name: 'Anh Duy',
    avatar: 'https://picsum.photos/150/150?random=4',
    bio: 'Coffee lover ☕\nMinimalist lifestyle',
    website: '',
    isVerified: false,
    isPrivate: false,
    postsCount: 45,
    followersCount: 234,
    followingCount: 123,
    isFollowing: true,
    isFollowedBy: false,
    isBlocked: false,
    isMuted: false,
  },
  {
    id: 'user5',
    username: 'bao5',
    name: 'Bảo',
    avatar: 'https://picsum.photos/150/150?random=5',
    bio: 'Music producer 🎵\nBeat maker',
    website: 'https://soundcloud.com/bao5',
    isVerified: false,
    isPrivate: false,
    postsCount: 67,
    followersCount: 789,
    followingCount: 345,
    isFollowing: false,
    isFollowedBy: true,
    isBlocked: false,
    isMuted: false,
  },
  {
    id: 'user6',
    username: 'huy.khn',
    name: 'Nguyễn Huy Khang',
    avatar: 'https://picsum.photos/150/150?random=6',
    bio: 'Fitness enthusiast 💪\nHealthy living advocate',
    website: '',
    isVerified: false,
    isPrivate: false,
    postsCount: 156,
    followersCount: 2300,
    followingCount: 678,
    isFollowing: true,
    isFollowedBy: true,
    isBlocked: false,
    isMuted: false,
  },
];

export const mockCurrentUser: UserProfile = {
  id: 'current',
  username: 'nghialc81',
  name: 'Lê Chí Nghĩa',
  avatar: 'https://picsum.photos/150/150?random=current',
  bio: 'Bình yên 🌸\nlocket.cam/nghialc',
  website: 'https://locket.cam/nghialc',
  isVerified: false,
  isPrivate: false,
  postsCount: 1,
  followersCount: 40,
  followingCount: 36,
  isFollowing: false,
  isFollowedBy: false,
  isBlocked: false,
  isMuted: false,
};